name: Build and deploy to bloki.app

on:
  push:
    branches: 
      - master

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Build frontend
      uses: pnpm/action-setup@v2.1.0
      with:
        version: 6.31.0
        run_install: true
    - run: pnpm build

    - name: Install node and packages
      uses: actions/setup-node@v2
      with:
        cache: 'pnpm'

    - name: Copy repository contents via rsync
      uses: easingthemes/ssh-deploy@main
      with:
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        REMOTE_PORT: ${{ secrets.PORT }}
        SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}
        SOURCE: "./dist/"
        TARGET: "/home/foxpro/bloki"
        ARGS: "-avzr --delete"

    - name: Restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: sudo systemctl restart bloki