name: bloki CI

on:
  push:
    branches:
      - master
      - preview/**
      - next

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.11.0

      - name: install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('./pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: pnpm install
        run: pnpm i --frozen-lockfile

      #   - name: install pw browsers
      #     working-directory: ./tests
      #     run: pnpx playwright install --with-deps

      #   - name: run tests
      #     run: pnpm test

      - name: build all
        run: pnpm build

      - name: publish cloudflare pages
        uses: cloudflare/wrangler-action@2.0.0
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        with:
          command: pages publish --project-name=bloki --commit-dirty=true ./dist/web/
          apiToken: ${{ secrets.CF_API_TOKEN }}

      - name: Notify telegram
        env:
          TG_KEY: ${{ secrets.TG_KEY }}
          TG_CHANNEL: ${{ secrets.TG_CHANNEL }}
        run: pnpm run -F tg start
