name: Build and deploy to bloki.app

on:
  push:
    branches: 
      - master

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
         ref: "master"
      
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Build frontend
      uses: pnpm/action-setup@v2.1.0
      with:
        version: 6.31.0
        run_install: true
    - run: pnpm build

    - name: Install node and packages
      uses: actions/setup-node@v2
      with:
        cache: 'pnpm'

    - name: Copy frontend via scp
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        # This is important to keep "/"
        source: "dist/" 
        target: "/home/deploy/bloki/dist"
        rm: true
        command_timeout: 1m
        strip_components: 1

    - name: Pull on server service
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: cd ./bloki && git pull && pnpm i && sudo systemctl restart bloki
        
    - name: Collect commit messages
      run: |  
         echo "messages=${{join(github.event.commits.*.message, '<pre>\n</pre>')}}" >> $GITHUB_ENV  
         echo "${{ env.messages }}"

    - name: Send tg message
      uses: appleboy/telegram-action@v0.1.1
      with:
         token: ${{ secrets.TG_KEY }}
         to: ${{ secrets.TG_CHANNEL }}
         format: 'html'
         message: |
            ${{ env.messages }}
            See changes: https://bloki.app