name: bloki ci

on:
  push:
    branches:
      - master
      - next
  release:
    types: [created]

env:
  IS_RELEASE: github.event_name == 'release' && github.event.action == 'created'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        env:
          TARGET_NAME: ${{ env.IS_RELEASE && 'bloki.app' || format('{0}.bloki.app', github.ref_name) }}

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('./pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: pnpm install
        run: pnpm i --frozen-lockfile

      - name: setup cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          # components: rustfmt, clippy

      # - name: install pw browsers
      #   if: ${{ env.IS_RELEASE }}
      #   working-directory: ./tests
      #   run: pnpx playwright install --with-deps

      # - name: run tests
      #   if: ${{ env.IS_RELEASE }}
      #   run: pnpm test

      - name: build all
        run: pnpm build

      - name: scp build
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: dist/api,dist/web
          target: /home/deploy/${{ env.TARGET_NAME }}
          overwrite: true
          command_timeout: 1m
          strip_components: 1

      - name: scp nginx file
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: ./misc/nginx/${{ env.TARGET_NAME }}.conf
          target: /etc/nginx/sites/
          overwrite: true
          command_timeout: 30s
          strip_components: 2

      - name: scp systemd file
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: ./misc/systemd/${{ env.TARGET_NAME }}.service
          target: /etc/systemd/system/
          overwrite: true
          command_timeout: 30s
          strip_components: 2

      - name: restart nginx and systemd ${{ env.TARGET_NAME }}
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            sudo nginx -s reload
            sudo systemctl reenable ${{ env.TARGET_NAME }}
            sudo systemctl restart ${{ env.TARGET_NAME }}

      - name: notify telegram
        env:
          TG_KEY: ${{ secrets.TG_KEY }}
          TG_CHANNEL: ${{ secrets.TG_CHANNEL }}
        run: pnpm run -F tg start
