name: next.bloki.app

on:
  push:
    branches:
      - next

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      CI: 1
      TG_KEY: ${{ secrets.TG_KEY }}
      TG_CHANNEL: ${{ secrets.RECEIVER_1 }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: "next"

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.0.1

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 17.9.0
          cache: "pnpm"

      - name: pnpm install
        run: pnpm i

      - name: install pw browsers
        working-directory: ./tests
        run: pnpx playwright install --with-deps

      - name: install dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: dotnet restore
        run: pnpm -F api restore

      - name: run tests
        run: pnpm test

      - name: build all
        run: pnpm build

      - name: copy via scp
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          # This is important to keep "/"
          source: "dist/api,dist/client"
          target: "/home/deploy/bloki-next"
          rm: true
          command_timeout: 1m
          strip_components: 1

      - name: Restart service bloki-next
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: sudo systemctl restart bloki-next

      - name: Notify telegram
        run: pnpm run -F tg-notifier start
